### ISSUE TITLE
Undefined variable: auth_data in AuthLDAP.php on line 21

### ISSUE THREAD

**Issue by zordanarres** [munkireport/munkireport-php#1006]
In version 3.0.2.3318 when using an LDAP configuration for user authentication, login fails with the following error message:
```
Notice: Undefined variable: auth_data in /munkireport/app/lib/munkireport/AuthLDAP.php on line 21

Warning: Invalid argument supplied for foreach() in /munkireport/app/lib/authLDAP/authLDAP.php on line 60
```

The configuration I use in config.php looks like the following:
```
$conf['auth']['auth_ldap']['server']      = 'server.pretendco.com'; // One or more servers separated by commas.
$conf['auth']['auth_ldap']['usertree']    = 'uid=%{user},cn=users,dc=server,dc=pretendco,dc=com'; // Where to find the user accounts.
$conf['auth']['auth_ldap']['grouptree']   = 'cn=groups,dc=server,dc=pretendco,dc=com'; // Where to find the groups.
$conf['auth']['auth_ldap']['mr_allowed_groups'] = array('munkiadmins'); // For group based access, fill in groups.
$conf['auth_secure'] = TRUE;
```

**Comment by jelockwood** [comment]
I appear to be getting the same issue -

I am trying to upgrade from MunkiReport-PHP 2.15.2 to MunkiReport-PHP 3.1.1.3370.

I had version 2.15.2 successfully configured to use LDAP authentication, however after installing 3.1.1.3370 and keeping my original config.php I now get the following error messages when I access the MunkiReport webpage.

Notice: Undefined property: munkireport\lib\AuthLDAP::$authStatus in /usr/local/munkireport-php/app/lib/munkireport/AuthLDAP.php on line 56

Notice: Undefined property: munkireport\lib\AuthLDAP::$authStatus in /usr/local/munkireport-php/app/lib/munkireport/AuthLDAP.php on line 56

(It is shown twice.)

Sadly the MunkiReport wiki does not cover LDAP use at all.

For what it's worth I am using FreeIPA as the LDAP server.

Here is my settings for LDAP from my config.php

```
                        $auth_config['myname'] = 'myhashedpassword';
                        $conf['auth']['auth_ldap']['server']      = 'ipa0.domain.com'; // One or more servers separated by commas.
                        $conf['auth']['auth_ldap']['usertree']    = 'uid=%{user},cn=users,cn=accounts,dc=domain,dc=com'; // Where to find the user accounts.
                        $conf['auth']['auth_ldap']['grouptree']   = 'cn=groups,cn=accounts,dc=domain,dc=com'; // Where to find the groups.
                        $conf['auth']['auth_ldap']['mr_allowed_groups'] = array('itsupport'); // For group based access, fill in groups.

                        $conf['auth']['auth_ldap']['userfilter']  = '(&(uid=%{user})(objectClass=posixAccount))'; // LDAP filter to search for user accounts.
                        $conf['auth']['auth_ldap']['groupfilter'] = '(&(objectClass=posixGroup)(cn=*))'; // LDAP filter to search for groups.
                        $conf['auth']['auth_ldap']['port']        = 389; // LDAP port.
                        $conf['auth']['auth_ldap']['version']     = 3; // Use LDAP version 1, 2 or 3.
                        $conf['auth']['auth_ldap']['starttls']    = TRUE; // Set to TRUE to use TLS.
//                      $conf['auth']['auth_ldap']['referrals']   = FALSE; // Set to TRUE to follow referrals.
//                      $conf['auth']['auth_ldap']['deref']       = LDAP_DEREF_NEVER; // How to dereference aliases. See http://php.net/ldap_search
                        $conf['auth']['auth_ldap']['userscope']   = 'sub'; // Limit search scope to sub, one or base.
                        $conf['auth']['auth_ldap']['groupscope']  = 'sub'; // Limit search scope to sub, one or base.
                        $conf['auth']['auth_ldap']['groupkey']    = 'cn'; // The key that is used to determine group membership
                        $conf['auth']['auth_ldap']['debug']       = TRUE; // Set to TRUE to debug LDAP.
```

Upon trying to login with LDAP credentials I then get -

Notice: Undefined variable: auth_data in /usr/local/munkireport-php/app/lib/munkireport/AuthLDAP.php on line 21

Warning: Invalid argument supplied for foreach() in /usr/local/munkireport-php/app/lib/authLDAP/authLDAP.php on line 60

Notice: Undefined property: munkireport\lib\AuthLDAP::$authStatus in /usr/local/munkireport-php/app/lib/munkireport/AuthLDAP.php on line 56

Notice: Undefined property: munkireport\lib\AuthLDAP::$authStatus in /usr/local/munkireport-php/app/lib/munkireport/AuthLDAP.php on line 56
×
LDAP: couldn't connect to LDAP server

**Comment by bochoven** [comment]
Could you try and use the auth_AD library, it should be ok for pure LDAP as well

**Comment by jelockwood** [comment]
@bochoven 

I hear what you say about trying auth_AD instead but Active Directory even though based on LDAP is significantly different. Whilst it might be possible to either not do authenticated binding to do a search and whilst not using a more specific tree for groups and users might not be necessary and one could try relying on sub-tree searches finding them, things like group membership checking is different enough between _real_ LDAP servers let alone LDAP and AD.

Having looked at the available AD vs LDAP settings in the config.php I have very little confidence this approach is workable.

I know another different PHP project I tried with much simpler requirements which comes hard-coded for AD connectivity would not talk to our LDAP and that did not even try to use group membership queries.

**Comment by bochoven** [comment]
There's a schema for different LDAP implementations (including Free IPA): https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md

**Comment by jelockwood** [comment]
@bochoven 

Ok, yes I see from the adldap2 docs it does support schemas and has one for FreeIPA. I can deduce from your last post that I presumably need to add a line to my config.php as folllows.

`'schema'           => \Adldap\Schemas\FreeIPA::class,`

The adldap2 documention here - https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md is poor, it is not clear how this fits in with the 'standard' structure in the config.php

What is also not clear from the adldap2 documentation is whether I need to download and install first the FreeIPA scheme and if so where it needs to be located, or ugh! to build a custom adldap2 with it compiled in to it.

I presume there is no likelihood of the LDAP code in MunkiReport-PHP3 being fixed?

I have over the years had to install and use numerous open source projects and some are straight forward and some are horrid, composer falls in to the later category.

**Comment by bochoven** [comment]
Hi John,

The FreeIPA schema is already present, so you could add it to the other `auth_AD` preferences

```
$conf['auth']['auth_AD']['scheme'] = \Adldap\Schemas\FreeIPA::class;
```

I'm pondering if it's helpful to make this a separate auth method but I want to make sure this works for you.

**Comment by jelockwood** [comment]
@bochoven 

Ok, I commented out my LDAP entries from my config.php and added uncommented auth_ad entries instead. I then restarted apache. I also included your line as follows.

`$conf['auth']['auth_AD']['scheme'] = \Adldap\Schemas\FreeIPA::class;`

Going to the MunkiReport page this time initially produced no error. I then tried to authenticate with the same LDAP user as before I then got the following error.

Not authorized
Option scheme does not exist.

I suspected 'scheme' should be 'schema' so tried that. I still got effectively the same error except it now complains about schema, same when trying 'schemas'.

This suggests either the FreeIPA schema is not installed in to adldap or more likely the naming of the option is wrong.

By the way this issue - https://github.com/Adldap2/Adldap2/issues/508 suggests you are using an obsolete version of adldap. (See last comment.)

**Comment by jelockwood** [comment]
@bochoven 
If MunkiReport-PHP is indeed using the older version of adldap this might explain why the schema option is not working since I believe that function is only available in adldap2.

Any likelihood of MunkiReport-PHP being updated to use the newer adldap2?

**Comment by bochoven** [comment]
Munkireport 3 is using adldap2

**Comment by jelockwood** [comment]
@bochoven 
I have been speaking to the developer of adldap2 and contrary to what its documentation implies the schema option is not yet supported in 8.x of adldap2.

If you go to https://github.com/Adldap2/Adldap2/issues/543#issuecomment-386350407 you will see this discussion and his comment on how to force adldap2 to use a different schema currently.

Based on this can you tell me if and how we can do this with MunkiReport? I think he is suggesting a modification to your AuthAD.php file as a temporary fix.

**Comment by bochoven** [comment]
Hey John, thanks for sorting that out. I made the modifications in a separate branch:

https://github.com/munkireport/munkireport-php/tree/FrreeIPA-support

Could you try and see if that works for you?

**Comment by jelockwood** [comment]
@bochoven 
It looks like that branch is now requiring php 7.1 is this correct? It seems php 7.1 is not in the standard repo for Ubuntu 16.04 LTS. I could install it from an unofficial repo but was hoping not to need to do that.

**Comment by bochoven** [comment]
I changed composer.json for 7.0 support

**Comment by jelockwood** [comment]
@bochoven Thanks for reverting to PHP7.0, that worked. However having now installed it and tried starting it I get the following errors.


`Fatal error: Uncaught Error: Undefined constant 'Adldap\Adldap\Schemas\OpenLDAP' in /usr/local/munkireport-php/app/lib/munkireport/AuthAD.php:6 Stack trace: #0 /usr/local/munkireport-php/vendor/composer/ClassLoader.php(444): include() #1 /usr/local/munkireport-php/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/usr/local/munk...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('munkireport\\lib...') #3 /usr/local/munkireport-php/app/lib/munkireport/AuthHandler.php(53): spl_autoload_call('munkireport\\lib...') #4 /usr/local/munkireport-php/app/lib/munkireport/AuthHandler.php(34): munkireport\lib\AuthHandler->validate('', '') #5 /usr/local/munkireport-php/app/controllers/auth.php(80): munkireport\lib\AuthHandler->login('', '') #6 /usr/local/munkireport-php/system/kissmvc_core.php(88): munkireport\controller\Auth->login() #7 /usr/local/munkireport-php/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') #8 /usr/local/munkireport-php/public/index.php(148): En in /usr/local/munkireport-php/app/lib/munkireport/AuthAD.php on line 6`

This happens whether I have the previous 

`$conf['auth']['auth_AD']['scheme'] = \Adldap\Schemas\FreeIPA::class;
`

included in the config.php or whether I remove that.

I can see it is referring to OpenLDAP and as a reminder I am using FreeIPA.

For what it's worth here is the results from composer although I don't think there is anything here to be concerned about.

```
/usr/local/munkireport-php$ composer install --no-dev --no-suggest --optimize-autoloader
Loading composer repositories with package information
Updating dependencies
Package operations: 30 installs, 0 updates, 0 removals
  - Installing hautelook/phpass (1.1.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.8.0): Downloading (100%)         
  - Installing symfony/translation (v3.4.9): Downloading (100%)         
  - Installing nesbot/carbon (1.27.0): Downloading (100%)         
  - Installing paragonie/random_compat (v2.0.12): Loading from cache
  - Installing illuminate/contracts (v5.4.36): Downloading (100%)         
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing illuminate/support (v5.4.36): Downloading (100%)         
  - Installing illuminate/container (v5.4.36): Downloading (100%)         
  - Installing illuminate/database (v5.4.36): Downloading (100%)         
  - Installing vlucas/phpdotenv (v2.4.0): Downloading (100%)         
  - Installing symfony/finder (v3.4.9): Loading from cache
  - Installing illuminate/filesystem (v5.4.36): Downloading (100%)         
  - Installing league/flysystem (1.0.45): Downloading (100%)         
  - Installing rodneyrehm/plist (v2.0.1): Downloading (100%)         
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)         
  - Installing doctrine/collections (v1.4.0): Loading from cache
  - Installing doctrine/cache (v1.6.2): Loading from cache
  - Installing doctrine/annotations (v1.4.0): Loading from cache
  - Installing doctrine/common (v2.7.3): Loading from cache
  - Installing doctrine/dbal (v2.5.13): Loading from cache
  - Installing defuse/php-encryption (v2.2.0): Downloading (100%)         
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)         
  - Installing psr/log (1.0.2): Downloading (100%)         
  - Installing symfony/debug (v3.4.9): Downloading (100%)         
  - Installing symfony/console (v3.4.9): Downloading (100%)         
  - Installing illuminate/console (v5.4.36): Downloading (100%)         
Writing lock file
Generating optimized autoload files

```

**Comment by bochoven** [comment]
Hi John,

I should have tested the code before I checked it in. I fixed the errors that you saw, so you should be good to go.

The new invocation is:

```
$conf['auth']['auth_AD']['schema'] = 'OpenLDAP';
```
or
```
$conf['auth']['auth_AD']['schema'] = 'FreeIPA';
```
or (default)
```
$conf['auth']['auth_AD']['schema'] = 'ActiveDirectory';
```

**Comment by jelockwood** [comment]
Ok, I downloaded the latest version and modified my line to

`$conf['auth']['auth_AD']['schema'] = 'FreeIPA';`

Unfortunately I am still getting a similar but not identical error as follows.


`Fatal error: Uncaught Error: Class 'Adldap\Schemas\FreeIPA' not found in /usr/local/munkireport-php/app/lib/munkireport/AuthAD.php:17 Stack trace: #0 /usr/local/munkireport-php/app/lib/munkireport/AuthHandler.php(53): munkireport\lib\AuthAD->__construct(Array, Object(munkireport\lib\AuthHandler)) #1 /usr/local/munkireport-php/app/lib/munkireport/AuthHandler.php(34): munkireport\lib\AuthHandler->validate('', '') #2 /usr/local/munkireport-php/app/controllers/auth.php(80): munkireport\lib\AuthHandler->login('', '') #3 /usr/local/munkireport-php/system/kissmvc_core.php(88): munkireport\controller\Auth->login() #4 /usr/local/munkireport-php/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') #5 /usr/local/munkireport-php/public/index.php(148): Engine->__construct(Array, 'show', 'index', 'AUTO') #6 {main} thrown in /usr/local/munkireport-php/app/lib/munkireport/AuthAD.php on line 17`

**Comment by bochoven** [comment]
It looks like you need to run 

composer install --no-dev --no-suggest --optimize-autoloader
again, that should resolve the path to the freeipa class

**Comment by jelockwood** [comment]
I had run that composer command and I have just done so again just in case. I had forgotten to change the ownership to www-data but I did that this time and I am still getting this error.

In case it is relevant I have a symbolic link to the **/usr/local/munkireport-php/public** folder as **/var/www/munkireport-php/public** I have set the document root in apache2 to /var/www/munkireport-php/public

As default Apache2 will not load content outside of **/var/www** and a symbolic link like this is a standard way to get round this.

**Comment by bochoven** [comment]
What does

```php
grep FreeIPA  vendor/composer/*
```

return?

**Comment by jelockwood** [comment]
That grep command returns nothing i.e. nothing found. I did (honest) run the composer command again when I tried the latest version.

For what it's worth here is the **ls** listing of vendor/composer/

```
-rw-rw-r-- 1 www-data www-data 123321 May 10 08:19 autoload_classmap.php
-rw-rw-r-- 1 www-data www-data    740 May 10 08:19 autoload_files.php
-rw-rw-r-- 1 www-data www-data    522 May 10 08:19 autoload_namespaces.php
-rw-rw-r-- 1 www-data www-data   2299 May 10 08:19 autoload_psr4.php
-rw-rw-r-- 1 www-data www-data   2414 May 10 08:19 autoload_real.php
-rw-rw-r-- 1 www-data www-data 140009 May 10 08:19 autoload_static.php
-rw-rw-r-- 1 www-data www-data  13420 May 10 08:19 ClassLoader.php
-rw-rw-r-- 1 www-data www-data  56364 May 10 08:19 installed.json
-rw-rw-r-- 1 www-data www-data   1070 May 10 08:19 LICENSE
```

**Comment by bochoven** [comment]
Did you run 

composer require adldap2/adldap2

prior to composer install?

**Comment by jelockwood** [comment]
I don't recall seeing that instruction anywhere. Doing it resulted in additional stuff being installed as below.

```
composer require adldap2/adldap2
Using version ^8.1 for adldap2/adldap2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 30 installs, 0 updates, 0 removals
  - Installing adldap2/adldap2 (v8.1.5): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing sebastian/version (2.0.1): Downloading (100%)         
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)         
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)         
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)         
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)         
  - Installing sebastian/global-state (2.0.0): Downloading (100%)         
  - Installing sebastian/exporter (3.1.0): Downloading (100%)         
  - Installing sebastian/environment (3.1.0): Downloading (100%)         
  - Installing sebastian/diff (2.0.1): Downloading (100%)         
  - Installing sebastian/comparator (2.1.3): Downloading (100%)         
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)         
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)         
  - Installing phpunit/phpunit-mock-objects (5.0.6): Downloading (100%)         
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)         
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)         
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)         
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)         
  - Installing phpunit/php-token-stream (2.0.2): Downloading (100%)         
  - Installing phpunit/php-code-coverage (5.3.2): Downloading (100%)         
  - Installing webmozart/assert (1.3.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)         
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-docblock (4.3.0): Downloading (100%)         
  - Installing phpspec/prophecy (1.7.6): Downloading (100%)         
  - Installing phar-io/version (1.0.1): Downloading (100%)         
  - Installing phar-io/manifest (1.0.1): Downloading (100%)         
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)         
  - Installing phpunit/phpunit (6.5.8): Downloading (100%)         
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
```

Doing composer install after the composer require adldap2 actually removed stuff as per below.

```
composer install --no-dev --no-suggest --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 29 removals
  - Removing webmozart/assert (1.3.0)
  - Removing theseer/tokenizer (1.1.0)
  - Removing squizlabs/php_codesniffer (2.9.1)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/resource-operations (1.0.0)
  - Removing sebastian/recursion-context (3.0.0)
  - Removing sebastian/object-reflector (1.1.1)
  - Removing sebastian/object-enumerator (3.0.3)
  - Removing sebastian/global-state (2.0.0)
  - Removing sebastian/exporter (3.1.0)
  - Removing sebastian/environment (3.1.0)
  - Removing sebastian/diff (2.0.1)
  - Removing sebastian/comparator (2.1.3)
  - Removing sebastian/code-unit-reverse-lookup (1.0.1)
  - Removing phpunit/phpunit-mock-objects (5.0.6)
  - Removing phpunit/phpunit (6.5.8)
  - Removing phpunit/php-token-stream (2.0.2)
  - Removing phpunit/php-timer (1.0.9)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (1.4.5)
  - Removing phpunit/php-code-coverage (5.3.2)
  - Removing phpspec/prophecy (1.7.6)
  - Removing phpdocumentor/type-resolver (0.4.0)
  - Removing phpdocumentor/reflection-docblock (4.3.0)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing phar-io/version (1.0.1)
  - Removing phar-io/manifest (1.0.1)
  - Removing myclabs/deep-copy (1.7.0)
  - Removing doctrine/instantiator (1.0.5)
Generating optimized autoload files
```

I am wondering if your composer.json has problems. Although after doing both the compose require and composer install I have now got past the previous error.

Now I get the following which is probably correct.

×
Not authorized
Option useTLS does not exist.

This will relate to the inclusion of

                        $conf['auth']['auth_AD']['useTLS'] = true;

I commented out that line and tried again. I then got

×
Wrong username or password

I now suspect we are on the home stretch. The number of parameters for auth_ad is smaller than auth_ldap and being the examples are targeted at AD rather than LDAP I may have incorrect values.

For FreeIPA it stores users in cn=users,cn=accounts,dc=example,dc=domain,dc=com it stores groups in cn=groups,cn=accounts,dc=example,dc=domain,dc=com as such this means usually using a basedn of cn=accounts,dc=example,dc=domain,dc=com

When I was using auth_ldap I was using TLS authentication. 

I managed to find the following from our FreeIPA server.

```
[11/May/2018:15:40:07 +0100] conn=125423 op=1 BIND dn="lockwojo" method=128 version=3
[11/May/2018:15:40:07 +0100] conn=125423 op=1 RESULT err=32 tag=97 nentries=0 etime=0
[11/May/2018:15:40:07 +0100] conn=125423 op=2 UNBIND
[11/May/2018:15:40:07 +0100] conn=125423 op=2 fd=138 closed - U1
[11/May/2018:15:40:09 +0100] conn=125235 op=8 UNBIND
[11/May/2018:15:40:09 +0100] conn=125235 op=8 fd=156 closed - U1
[11/May/2018:15:40:09 +0100] conn=5 op=923181 SRCH base="dc=internal,dc=yoti,dc=com" scope=2 filter="(&(|(objectClass=krbprincipalaux)(objectClass=krbprincipal)(objectClass=ipakrbprincipal))(|(ipaKrbPrincipalAlias=krbtgt/INTERNAL.YOTI.COM@INTERNAL.YOTI.COM)(krbPrincipalName=krbtgt/INTERNAL.YOTI.COM@INTERNAL.YOTI.COM)))" attrs="krbPrincipalName krbCanonicalName ipaKrbPrincipalAlias krbUPEnabled krbPrincipalKey krbTicketPolicyReference krbPrincipalExpiration krbPasswordExpiration krbPwdPolicyReference krbPrincipalType krbPwdHistory krbLastPwdChange krbPrincipalAliases krbLastSuccessfulAuth krbLastFailedAuth krbLoginFailedCount krbExtraData krbLastAdminUnlock krbObjectReferences krbTicketFlags krbMaxTicketLife krbMaxRenewableAge nsAccountLock passwordHistory ipaKrbAuthzData ipaUserAuthType ipatokenRadiusConfigLink objectClass"
[11/May/2018:15:40:09 +0100] conn=5 op=923181 RESULT err=0 tag=101 nentries=1 etime=0
```
Tried adding admin and pass but that made things worse if anything MunkiReport then said

An error occurred while contacting AD
No such object

**Comment by bochoven** [comment]
Options for adlap2 are listed here:

https://github.com/Adldap2/Adldap2/blob/master/docs/configuration.md

For instance: 

```
$conf['auth']['auth_AD']['use_tls'] = true;
```

**Comment by bochoven** [comment]
I got munkireport to authenticate against FreeIPA with a slight modification to`AuthAD.php` (now pushed to the FreeIPA branch) and the following config:

```php
$conf['auth']['auth_AD'] = [
  'base_dn'                  => 'dc=demo1,dc=freeipa,dc=org',
  'domain_controllers'       => ['ipa.demo1.freeipa.org'],
  'account_prefix'           => 'uid=',
  'account_suffix'           => ',cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org',
  'schema'                   => 'FreeIPA',
  // 'use_tls'                   => true,
  'mr_allowed_users'         => [],
  'mr_allowed_groups'        => ['employees'],
  'mr_recursive_groupsearch' => false,
];
```
I am using the FreeIPA demo server as described here: https://www.freeipa.org/page/Demo

**Comment by jelockwood** [comment]
Ok, thanks for your latest answers. It looks like we are very close. I think there is a problem with checking for group membership as with that line active it fails, with it commented out it works. It is not giving a syntax error from the config.php it is looking more like the group membership test is simply failing.

The other issue I am now encountering is that having with the above caveat got past authentication, I now have a MySQL connectivity issue because of the change in that area from the old PDO config to the new Eloquent config.

I can see your documentation on that here - https://github.com/munkireport/munkireport-php/wiki/How-to-Upgrade-to-v3 but it does not cover using an SSL connection to the MySQL server. As a comparison here is my previous PDO config.

```
        $conf['pdo_dsn'] = 'mysql:host=it-db.example.com;dbname=munkireport;port=3306';
        $conf['pdo_user'] = 'munkireport';
        $conf['pdo_pass'] = 'password';
        $conf['pdo_opts'] = array(
                        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
                        PDO::MYSQL_ATTR_SSL_KEY => '/etc/mysql/ssl/munki.example.com.key',
                        PDO::MYSQL_ATTR_SSL_CERT => '/etc/mysql/ssl/munki.example.com.crt',
                        PDO::MYSQL_ATTR_SSL_CA => '/etc/mysql/ssl/exampleCA.crt'
                                );
```
How would I include equivalent SSL settings with the new Eloquent approach?

**Comment by bochoven** [comment]
Hi John, I did not encounter any issues using group membership, so I would be interested in your findings. You can check group membership of a logged-in user by visiting: 

https://MFQDN/index.php?/auth/set_session_props/1

As for the MySQL SSL question: please open a separate issue for that.

**Comment by jelockwood** [comment]
Ok, it turns out I had made a silly typo with the MySQL settings, that once fixed is now working fine, _with SSL_.

I then tried your command above and could see it was listing the correct group, I then tried the line again and this time it works. So now both authentication and MySQL with SSL are working. Not sure why the group line did not originally work but happy it now does.

It would seem that you can now commit these changes to the main branch as FreeIPA is now working for me.

I do have a couple of MySQL errors but as advised will open a new ticket.

**Comment by bochoven** [comment]
#1079 should fix this
