### ISSUE TITLE
Just upgraded to 2.4.2 lots of errors in profiles page

### ISSUE THREAD

**Issue by kcrawshaw** [munkireport/munkireport-php#249]
Just performed the upgrade to 2.4.2 from 2.3.0 and profile reporting appears to be working, but when I go to the 'Profile' listing page it displays the following like 15 times.
`Warning: gzinflate(): data error in /usr/share/nginx/html/report/system/kissmvc_core.php on line 630`

If I view any individual machine's 'Profile' section I see the following:
`Notice: Undefined variable: profiles in /usr/share/nginx/html/report/system/kissmvc_core.php(316) : eval()'d code on line 20`

The profiles are visible and I can view the payload, but I have those errors in MunkiReportPHP. Not sure if this is a bug or if I messed something up.

**Comment by bochoven** [comment]
Oww, I missed that one. I fixed it a month ago, but apparently failed to add it to the master branch. Could you check out the current master branch and see if it fixes your issue? You might have to drop the profiles table.

**Comment by kcrawshaw** [comment]
Thanks for responding and acting on this so quickly! I am not longer seeing the gzipinflate() warning, but I do still see 
`
Notice: Undefined variable: profiles in /usr/share/nginx/html/report/system/kissmvc_core.php(316) : eval()'d code on line 20
` when I go to view an individual machines profile listing. I did drop the profile table as well. Should I drop the machine table as well?

**Comment by kcrawshaw** [comment]
Works as expected now!
