### ISSUE TITLE
[3.] Call to undefined method Adldap\Models\Computer::getGroupNames()

### ISSUE THREAD

**Issue by LucasjHall** [munkireport/munkireport-php#974]
### Error
```
Fatal error: Uncaught Error: Call to undefined method Adldap\Models\Computer::getGroupNames() in /${webroot}/munkireport-php/app/lib/munkireport/AuthAD.php:31 
```
### Sanitized Stack Trace:
```
Stack trace: 
#0 /${webroot}/munkireport-php/app/lib/munkireport/AuthHandler.php(54): munkireport\lib\AuthAD->login('${usr}', '${psw}') 
#1 /${webroot}/munkireport-php/app/lib/munkireport/AuthHandler.php(34): munkireport\lib\AuthHandler->validate('${usr}', '${psw}') 
#2 /${webroot}/munkireport-php/app/controllers/auth.php(74): munkireport\lib\AuthHandler->login('${usr}', '${psw}') 
#3 /${webroot}/munkireport-php/system/kissmvc_core.php(88): munkireport\controller\Auth->login() 
#4 /${webroot}/munkireport-php/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') 
#5 /${webroot}/munkireport-php/public/index.php(147): Engine->__construct(Array, 'show', 'index', 'AUTO') 
#6 {main} thrown in /${webroot}/munkireport-php/app/lib/munkireport/AuthAD.php on line 31
```
Ref [line](https://github.com/munkireport/munkireport-php/blob/a6b8e397995c3fd06ccea3d6ac70ef7c2a247485/app/lib/munkireport/AuthAD.php#L31). 

MR: `v3.0.1.3295`

**Comment by bochoven** [comment]
I see what goes wrong here, AD contains a computer object with the same name as the user that is logging in.

**Comment by LucasjHall** [comment]
@bochoven I checked if that was the case, and it doesn't seem so, the username might be contained within a computer name, but there is no case of username being the same as the computer name. Would that trigger this as well? Is there anyway to workaround/fix this issue?

**Comment by bochoven** [comment]
I think the authAD plugin needs some improvement. Currently it searches the whole AD: 
```
$user = $search->findOrFail($login);
```
 It should only search in user objects.

**Comment by bochoven** [comment]
I pushed a new commit that limits the search scope to users.

https://github.com/munkireport/munkireport-php/commit/84986df84ce07e84e210a4ded2fa29cf58ff7abc

Please let me know if that fixes the issue.

**Comment by LucasjHall** [comment]
- I pulled wip,
-- Same stack trace, verbatim. 
- I re-ran composer after pull of WIP.
-- Same stack trace.
- Restarted needed services etc
-- Still the same stack trace.

**Comment by LucasjHall** [comment]
@bochoven 

Pulled 778132f6d8cfe2bff47e447c67bfc7c36a5075b3 and LDAP issue is confirmed resolved on `3.1.1.3364`

Thanks!
